# -*- coding: utf-8 -*-
"""Exp. 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lv3TS2ZNy1sQo8A_42PRiPt5R6kzabY3
"""

import pandas as pd
import numpy as np

df = pd.read_excel("/content/Salary_Dataset_02.xls")
df.head()

# In X we store predictor variables.
X = df.iloc[:,:-1]
#In y we store target variables.
y = df.iloc[:,-1]

"""#Divide Data as Training Set and Testing Set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 90)

print(X_train)

print(X_test)

print(y_test)

print(y_test)