# -*- coding: utf-8 -*-
"""Handling missing Values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPZJl0wx5hP950y7mlpDE-ZnYPNPNW_g
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

dataset = pd.read_csv('/content/student_admission_record_dirty.csv')

dataset.head()

dataset.shape

dataset.isnull().sum()

"""#Analysing distribution of data in Age"""

fig,ax = plt.subplots(figsize=(4,4))
sn.distplot(dataset.Age)

"""# 1.MEAN
# 2.MEDIAN
# 3.MODE

**Replacing Value using Mean**
"""

dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)

dataset.isnull().sum()

"""**Replacing Value using Median**"""

dataset['Age'].fillna(dataset['Age'].median(),inplace=True)

dataset.isnull().sum()

dataset.head(20)

df = dataset.dropna(how='any')

df.isnull().sum()

df.head()